routes/web.php
                Route::get('update-settings/manual-update', ['uses' => 'UpdateDatabaseController@manual'])->name('update-settings.manual');
                Route::resource('update-settings', 'UpdateDatabaseController');

                // Language Settings
                Route::post('language-settings/update-data/{id?}', ['uses' => 'SuperAdminLanguageSettingsController@updateData'])->name('language-settings.update-data');
                Route::resource('language-settings', 'SuperAdminLanguageSettingsController');

                Route::resource('front-settings', 'SuperAdminFrontSettingController', ['only' => ['index', 'update']]);
                Route::resource('package-settings', 'SuperAdminPackageSettingController', ['only' => ['index', 'update']]);

                Route::resource('feature-settings', 'SuperAdminFeatureSettingController');
                Route::resource('footer-settings', 'SuperAdminFooterSettingController');

            }
        );

        Route::post('activity/store-cat', ['uses' => 'BoqCategoryController@storeCat'])->name('activity.store-cat');
        Route::get('activity/create-cat', ['uses' => 'BoqCategoryController@createCat'])->name('activity.create-cat');
        Route::get('activity/edit-cat/{id}', ['uses' => 'BoqCategoryController@editCat'])->name('activity.edit-cat');
        Route::post('activity/update-cat/{id}', ['uses' => 'BoqCategoryController@updateCat'])->name('activity.update-cat');
        Route::resource('activity', 'BoqCategoryController');

        Route::post('task/store-cat', ['uses' => 'ManageCostItemsController@storeCat'])->name('task.store-cat');
        Route::get('task/create-cat', ['uses' => 'ManageCostItemsController@createCat'])->name('task.create-cat');
        Route::get('task/edit-cat/{id}', ['uses' => 'ManageCostItemsController@editCat'])->name('task.edit-cat');
        Route::post('task/update-cat/{id}', ['uses' => 'ManageCostItemsController@updateCat'])->name('task.update-cat');
        Route::post('task/get-cost', ['uses' => 'ManageCostItemsController@getCost'])->name('task.getCost');
        Route::match(['get','post'],'task/product-add/{id}', ['uses' => 'ManageCostItemsController@productAdd'])->name('task.product-add');
        Route::match(['get','post'],'task/product-edit/{id}', ['uses' => 'ManageCostItemsController@productEdit'])->name('task.product-edit');
        Route::post('task/update-product/{id}', ['uses' => 'ManageCostItemsController@productUpdate'])->name('task.update-product');
        Route::delete('task/destroy-product/{id}', ['uses' => 'ManageCostItemsController@destroyProduct'])->name('task.destroy-product');
        //Route::get('task/data', ['uses' => 'CostItemsController@data'])->name('task.data');
        //Route::get('task/data', ['as' => 'task.data', 'uses' => 'CostItemsController@data']);

       /* Route::post('task/store-product/{id}', ['uses' => 'ManageCostItemsController@storeProduct'])->name('task.store-product');
        Route::post('task/name-store', ['uses' => 'CostItemsController@nameStore'])->name('task.namestore');*/
        Route::resource('task', 'ManageCostItemsController');

        Route::get('product-category/index', ['uses' => 'ManageProductCategoryController@index'])->name('productCategory.index');
        Route::resource('product-category', 'ManageProductCategoryController');

        Route::get('product-brand/index', ['uses' => 'ManageProductBrandController@index'])->name('productBrand.index');
        Route::resource('product-brand', 'ManageProductBrandController');

        Route::get('manage-modules/assign-permissions', ['uses' => 'SuperAdminManageModuleController@assignPermissions'])->name('manageModules.assignPermissions');
        Route::post('manage-modules/store-assign-permissions', ['uses' => 'SuperAdminManageModuleController@storeAssignPermissions'])->name('manageModules.storeAssignPermissions');
        Route::delete('manage-modules/remove-permissions/{id}', ['uses'=> 'SuperAdminManageModuleController@removePermissions'])->name('manageModules.removePermissions');
        Route::match(['get','post'],'manage-modules/get-permissions', ['uses' => 'SuperAdminManageModuleController@getPermissions'])->name('manageModules.getPermissions');
        Route::resource('manageModules', 'SuperAdminManageModuleController');

        Route::get('app-notification', ['uses' => 'SuperAdminController@appNotification'])->name('appNotification');
        Route::post('app-notification/send-notification', ['uses' => 'SuperAdminController@sendNotification'])->name('appNotification.sendNotification');
        //Promotional Notification
        Route::get('promotional-notification', ['uses' => 'SuperAdminController@promotionalNotification'])->name('promotionalNotification');
        Route::post('promotional-notification/send-notification', ['uses' => 'SuperAdminController@promotionalSendNotification'])->name('promotionalNotification.sendNotification');
    });

    // Admin routes
    Route::group(
        ['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['admin']],
        function () {

            Route::get('workers/workerdData', ['uses' => 'ManageWorkersController@workerdData'])->name('workers.workerData');

            Route::group(['middleware' => ['account-setup', 'license-expire']], function () {

                Route::match(['get','post'],'/dashboard', 'AdminDashboardController@index')->name('dashboard');
                Route::post('/dashboard/widget', 'AdminDashboardController@widget')->name('dashboard.widget');

                Route::get('designations/quick-create', ['uses' => 'ManageDesignationController@quickCreate'])->name('designations.quick-create');
                Route::post('designations/quick-store', ['uses' => 'ManageDesignationController@quickStore'])->name('designations.quick-store');
                Route::get('designations/data', ['uses' => 'ManageDesignationController@getDesignationData'])->name('designations.getDesignationData');
                Route::resource('designations', 'ManageDesignationController');
                // Location
                Route::post('location/store-cat', ['uses' => 'ManageLocationController@storeCat'])->name('location.store-cat');
                Route::get('location/create-cat', ['uses' => 'ManageLocationController@createCat'])->name('location.create-cat');
                Route::get('location/edit-cat/{id}', ['uses' => 'ManageLocationController@editCat'])->name('location.edit-cat');
                Route::post('location/update-cat/{id}', ['uses' => 'ManageLocationController@updateCat'])->name('location.update-cat');
                Route::post('location/get-city/{id}', ['uses' => 'ManageLocationController@getCity'])->name('location.get-city');
                Route::resource('location', 'ManageLocationController');
                Route::post('location/store-sub-cat', ['uses' => 'ManageLocationController@storesubCat'])->name('location.store-sub-cat');
                Route::get('location/sub-edit/{id}', ['uses' => 'ManageLocationController@editsubCat'])->name('location.sub-edit');
                Route::post('location/sub-update/{id}', ['uses' => 'ManageLocationController@updatesubCat'])->name('location.sub-update');
                Route::post('location/delete-sub-cat/{id}', ['uses' => 'ManageLocationController@deletesubCat'])->name('location.delete-sub-cat');
                Route::get('location/location-edit/{id}', ['uses' => 'ManageLocationController@editLocation'])->name('location.location-edit');
                Route::post('location/location-update/{id}', ['uses' => 'ManageLocationController@updateLocation'])->name('location.location-update');
                Route::post('location/delete-location/{id}', ['uses' => 'ManageLocationController@deleteLocation'])->name('location.delete-location');

                //Asset
                Route::post('asset-category/create-asset-cat', ['uses' => 'AssetCategoryController@createassetCat'])->name('asset-category.create-asset-cat');
                Route::get('asset-category/create-asset-edit/{id}', ['uses' => 'AssetCategoryController@editassetCat'])->name('asset-category.edit-asset-cat');
                Route::post('asset-category/update-asset-edit/{id}', ['uses' => 'AssetCategoryController@updateassetCat'])->name('asset-category.update-asset-cat');
                Route::get('asset-category/assets', ['uses' => 'AssetCategoryController@assets'])->name('asset-category.assets');
                Route::post('asset-category/create-asset', ['uses' => 'AssetCategoryController@createAsset'])->name('asset-category.create-asset');
                Route::get('asset-category/edit-asset/{id}', ['uses' => 'AssetCategoryController@editAsset'])->name('asset-category.edit-asset');
                Route::post('asset-category/update-asset/{id}', ['uses' => 'AssetCategoryController@updateAsset'])->name('asset-category.update-asset');
                Route::post('location/delete-asset/{id}', ['uses' => 'AssetCategoryController@deleteAsset'])->name('asset-category.delete-asset');
                Route::get('asset-category/sub-asset', ['uses' => 'AssetCategoryController@subAsset'])->name('asset-category.sub-asset');
                Route::post('asset-category/create-sub-asset', ['uses' => 'AssetCategoryController@createSubAsset'])->name('asset-category.create-sub-asset');
                Route::get('asset-category/edit-sub-asset/{id}', ['uses' => 'AssetCategoryController@editSubAsset'])->name('asset-category.edit-sub-asset');
                Route::post('asset-category/update-sub-asset/{id}', ['uses' => 'AssetCategoryController@updateSubAsset'])->name('asset-category.update-sub-asset');
                Route::post('location/delete-sub-asset/{id}', ['uses' => 'AssetCategoryController@deleteSubAsset'])->name('asset-category.delete-sub-asset');

                Route::resource('asset-category', 'AssetCategoryController');

                // Work Request and Work Order

app/ProductBrand.php
<?php

namespace App;

use App\Observers\ProductObserver;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class ProductBrand extends Model
{
    protected $table = 'brand';

//    protected $fillable = ['name', 'price', 'tax_id'];
//    protected $appends = ['total_amount'];
//
//    protected static function boot()
//    {
//        parent::boot();
//
//        static::observe(ProductObserver::class);
//
//        $company = company();
//
//        static::addGlobalScope('company', function (Builder $builder) use($company) {
//            if ($company) {
//                $builder->where('products.company_id', '=', $company->id);
//            }
//        });
//    }
//
//    public function tax()
//    {
//        return $this->belongsTo(Tax::class);
//    }
//
//    public static function taxbyid($id) {
//        return Tax::where('id', $id);
//    }
//
//    public function getTotalAmountAttribute(){
//
//        if(!is_null($this->price) && !is_null($this->tax)){
//            return $this->price + ($this->price * ($this->tax->rate_percent/100));
//        }
//
//        return "";
//    }
}

app/Http/Controllers/Admin/ProductBrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\Reply;
use App\Http\Requests\Boq\StoreBoqCategory;
use App\Http\Requests\ProductBrand\StoreProBrandRequest;
use App\ProductBrand;
use App\ProductCategory;
use Illuminate\Http\Request;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\DataTables;

class ProductBrandController extends AdminBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = 'Product Brands';
        $this->pageIcon = 'icon-user';
        $this->activeMenu = 'store';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->categories = ProductBrand::all();
        return view('admin.product-brand.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->categories = BoqCategory::all();
        return view('admin.boq-category.create', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createCat()
    {
        $this->categories = BoqCategory::all();
        return view('admin.boq-category.index', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBoqCategory $request)
    {
        $category = new BoqCategory();
        $category->title = $request->title;
        $category->parent = $request->parent;
        $category->save();

        return Reply::success(__('messages.categoryAdded'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeCat(StoreBoqCategory $request)
    {
        $category = new BoqCategory();
        $category->category_name = $request->category_name;
        $category->save();
        $categoryData = BoqCategory::all();
        return Reply::successWithData(__('messages.categoryAdded'),['data' => $categoryData]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->categories = BoqCategory::all();
        $this->category = BoqCategory::where('id',$id)->first();
        return view('admin.boq-category.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = BoqCategory::find($id);
        $category->title = $request->title;
        $category->parent = $request->parent;
        $category->save();

        return Reply::success(__('messages.categoryAdded'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BoqCategory::destroy($id);
        $categoryData = BoqCategory::all();
        return Reply::successWithData(__('messages.categoryDeleted'),['data' => $categoryData]);
    }

    public function data()
    {
        $products = ProductBrand::select('id', 'name')->get();

        return DataTables::of($products)
            ->editColumn('name', function ($row) {
                return ucfirst($row->name);
            })
            
            ->make(true);
    }

    public function addBrand(){
        return view('admin.product-brand.create',$this->data);
    }
    public function postBrand(StoreProBrandRequest $request){
        $brand  = new ProductBrand();
        $brand->name = $request->name;
        $brand->company_id = $this->companyid;
        $brand->save();
        return Reply::success(__('Brand Added Successfully!!'));
    }
    public function brandData(){
        $brandData = ProductBrand::where('company_id',$this->companyid)->get();
        return DataTables::of($brandData)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
                return '<a onclick="showEditBrand('.$row->id.')" class="btn btn-info btn-circle"
                      data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>

                      <a href="javascript:;" class="btn btn-danger btn-circle sa-params"
                      data-toggle="tooltip" data-user-id="' . $row->id . '" data-original-title="Delete"><i class="fa fa-times" aria-hidden="true"></i></a>';
            })
            ->editColumn('name', function ($row) {
                return $row->name;
            })
            ->rawColumns(['action'])
            ->make(true);
    }
    public function editBrand($id){
        $this->brands = ProductBrand::find($id);
        return view('admin.product-brand.edit',$this->data);
    }
    public function updateBrand(StoreProBrandRequest $request){

        $brand  = ProductBrand::find($request->rowid);
        $brand->name = $request->name;
        $brand->company_id = $this->companyid;
        $brand->save();
        return Reply::success(__('Brand Updated Successfully!!'));
    }
    public function destroyBrand($id){
        ProductBrand::destroy($id);
        return Reply::success(__('Brand Deleted Successfully!!'));
    }
}

resources/views/admin/initial-income-expense-head-balance/product-brand/create.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"> <i class="fa fa-plus"></i>Brand</h4>
</div>
<div class="modal-body">
    {!! Form::open(array('id' => 'add_brand_form', 'class'=>'form-horizontal ','method'=>'POST')) !!}
    <div class="form-body">
        <div class="row">
            <div id="addMoreBox1" class="clearfix">
                <div class="col-md-12">
                    <div id="dateBox" class="form-group ">
                        <label>Brand Name</label>
                        <input class="form-control" autocomplete="off" id="name"  name="name" type="text" value="" placeholder="Enter Brand Name"/>
                        <div id="errorDate"></div>
                    </div>
                </div>

            </div>
        </div>
        <!--/row-->
    </div>
    {!! Form::close() !!}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-white waves-effect" data-dismiss="modal">Close</button>
    <button type="button" onclick="storeBrand()" class="btn btn-info save-event waves-effect waves-light"><i class="fa fa-check"></i> @lang('app.save')
    </button>
</div>
<script>
    // Store Holidays
    function storeBrand(){
        var name = $('#name').val();
        var url = "{{ route('admin.productBrand.postBrand') }}";
        $.easyAjax({
            type: 'POST',
            url: url,
            container: '#add_brand_form',
            data: $('#add_brand_form').serialize(),
            success: function (response) {
                $('#add-brand-form').modal('hide');
                loadTable();
            }
        });
    }
</script>

resources/views/admin/initial-income-expense-head-balance/product-brand/edit.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"> <i class="fa fa-plus"></i>Brand</h4>
</div>
<div class="modal-body">
    {!! Form::open(array('id' => 'update_brand_form', 'class'=>'form-horizontal ','method'=>'POST')) !!}
    <div class="form-body">
        <div class="row">
            <div id="addMoreBox1" class="clearfix">
                <div class="col-md-12">
                    <input type="hidden" id="rowid" name="rowid" value="{{$brands->id}}">
                    <div id="dateBox" class="form-group ">
                        <label>Brand Name</label>
                        <input class="form-control" autocomplete="off" id="name"  name="name" type="text" @if(!empty($brands)) value="{{$brands->name}}" @endif placeholder="Enter Brand Name"/>
                        <div id="errorDate"></div>
                    </div>
                </div>

            </div>
        </div>
        <!--/row-->
    </div>
    {!! Form::close() !!}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-white waves-effect" data-dismiss="modal">Close</button>
    <button type="button" onclick="updateBrand()" class="btn btn-info save-event waves-effect waves-light"><i class="fa fa-check"></i> @lang('app.save')
    </button>
</div>
<script>
    // Store Holidays
    function updateBrand(){
        var rowid = $('#rowid').val();
        var name = $('#name').val();
        var url = "{{ route('admin.productBrand.updateBrand') }}";
        $.easyAjax({
            type: 'POST',
            url: url,
            container: '#update_brand_form',
            data: $('#update_brand_form').serialize(),
            success: function (response) {
                $('#edit-brand-form').modal('hide');
                loadTable();
            }
        });
    }
</script>

resources/views/admin/initial-income-expense-head-balance/product-brand/index.blade.php
@extends('layouts.app')

@section('page-title')
    <div class="row bg-title">
        <!-- .page title -->
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title" style="color: #002f76"><i class="{{ $pageIcon }}"></i> {{ __($pageTitle) }}</h4>
        </div>
        <!-- /.page title -->
        <!-- .breadcrumb -->
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}">@lang('app.menu.home')</a></li>
                <li class="active">{{ __($pageTitle) }}</li>
            </ol>
        </div>
        <!-- /.breadcrumb -->
    </div>
@endsection

@push('head-script')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">
<link rel="stylesheet" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/custom-select/custom-select.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/multiselect/css/multi-select.css') }}">
@endpush

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group pull-left">
                            <a onclick="showAdd()" class="btn btn-outline btn-success btn-sm ">Add Brand<i class="fa fa-plus" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table" id="example">
                        <thead>
                        <tr>
                            <th>@lang('app.sno')</th>
                            <th>Brand Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- .row -->
    {{--Ajax Modal--}}
    <div class="modal fade bs-modal-md in" id="add-brand-form" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn blue">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    {{--Ajax Modal Ends--}}

    {{--Ajax Modal--}}
    <div class="modal fade bs-modal-md in" id="edit-brand-form" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn blue">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    {{--Ajax Modal Ends--}}
@endsection

@push('footer-script')
<script src="{{ asset('plugins/bower_components/datatables/jquery.dataTables.min.js') }}"></script>
<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
<script src="{{ asset('plugins/bower_components/custom-select/custom-select.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/multiselect/js/jquery.multi-select.js') }}"></script>
<style>
    .select2-container-multi .select2-choices .select2-search-choice {
        background: #ffffff !important;
    }
</style>
<script>
    // Show Create Holiday Modal
    function showAdd() {
        var url = "{{ route('admin.productBrand.addBrand') }}";
        $.ajaxModal('#add-brand-form', url);
    }
    function showEditBrand(id) {
        var url = "{{ route('admin.productBrand.editBrand',':id')}}";
        url = url.replace(':id', id);
        $.ajaxModal('#edit-brand-form', url);
    }
    var table;
    $(function() {
        loadTable();
        $('body').on('click', '.sa-params', function(){
            var id = $(this).data('user-id');
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover the deleted user!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel please!",
                closeOnConfirm: true,
                closeOnCancel: true
            }, function(isConfirm){
                if (isConfirm) {
                    var url = "{{ route('admin.productBrand.destroyBrand',':id') }}";
                    url = url.replace(':id', id);
                    var token = "{{ csrf_token() }}";
                    $.easyAjax({
                        type: 'POST',
                        url: url,
                        data: {'_token': token, '_method': 'DELETE'},
                        success: function (response) {
                            if (response.status == "success"){
                                $.unblockUI();
//                                    swal("Deleted!", response.message, "success");
                                table._fnDraw();
                            }
                        }
                    });
                }
            });
        });

    });

    function loadTable() {
        table = $('#example').dataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            destroy: true,
            stateSave: true,
            ajax: '{!! route('admin.productBrand.data') !!}',
            language: {
                "url": "<?php echo __("app.datatable") ?>"
            },
            "fnDrawCallback": function (oSettings) {
                $("body").tooltip({
                    selector: '[data-toggle="tooltip"]'
                });
            },
            columns: [
                { data: 'DT_RowIndex', orderable: false, searchable: false },
                {data: 'name', name: 'name'},
                {data: 'action', name: 'action'}
            ]
        })
    }

</script>
@endpush